language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lazy-templates' ]; then cd .. && eval "mv $currentfolder generator-lazy-templates" && cd generator-lazy-templates; fi
