os: Visual Studio 2015

  
install:
 - ps: npm install -g gulp
 - ps: npm install -g bower
 


build_script:
  # dotnet info
  - ps: dir
  - ps: cd generators\app\templates\MainSolutionTemplate
  - ps: dir
  - ps: .\go.cmd


test: off 
version: 0.0.1.{build}
