os: Visual Studio 2015

  
install:
# - ps: npm install npm -g
# - ps: npm version
# - ps: npm install -g graceful-fs graceful-fs@latest
# - ps: npm install -g lodash lodash@latest
 - call npm install -g gulp
 - call npm install -g bower
 - choco install mongodb



build_script:
  # dotnet info
  - call dir C:\Program Files (x86)\mongodb
  - call dir C:\Program Files\mongodb
  - call dir C:\mongodb
  - call dir C:\Program Files\
  - ps: cd generators\app\templates\MainSolutionTemplate
  - ps: dir
  - ps: .\go.cmd appveyor


test: off 
version: 0.0.1.{build}
