os: Visual Studio 2015

  
install:
 - ps: npm install npm -g
 - ps: npm version
 - ps: npm install -g graceful-fs graceful-fs@latest
 - ps: npm install -g lodash lodash@latest
 - ps: call npm install -g gulp
 - ps: call npm install -g bower
 


build_script:
  # dotnet info
  - ps: dir
  - ps: cd generators\app\templates\MainSolutionTemplate
  - ps: dir
  - ps: .\go.cmd


test: off 
version: 0.0.1.{build}
